/**
 * Consistency-rule tests, one hand-built observation sequence per rule, plus the
 * false-positive guard: readings generated by the brain's own physics flag nothing.
 */
import { describe, expect, it } from 'vitest';
import { checkConsistency, updateHistory, type SensorHistory } from './consistency';
import { forward } from './physics';
import type { Observation, Reading, SpaceId, StructurePlan } from '../shared/types';

const line = (n: number, kind: 'door' | 'bulkhead' = 'door'): StructurePlan => ({
  name: `line-${n}`,
  ambient: 20,
  spaces: Array.from({ length: n }, (_, i) => ({ id: `S${i + 1}`, level: 1 })),
  edges: Array.from({ length: n - 1 }, (_, i) => ({ a: `S${i + 1}`, b: `S${i + 2}`, kind, rate: 0.15 })),
  sensors: Array.from({ length: n }, (_, i) => ({ id: `F${i + 1}`, spaceId: `S${i + 1}` })),
  resupply: ['S1'],
  ignition: ['S1'],
});

const reading = (sensorId: string, spaceId: string, temp: number, t: number): Reading => ({
  sensorId,
  source: 'fixed',
  spaceId,
  temp,
  t,
});

const obs = (t: number, readings: Reading[]): Observation => ({ t, readings, drones: [] });

const ambientEstimate = (plan: StructurePlan): Record<SpaceId, number> =>
  Object.fromEntries(plan.spaces.map((s) => [s.id, plan.ambient]));

describe('checkConsistency', () => {
  it('stale: a reading whose t lags obs.t by more than 2 is dropped', () => {
    const plan = line(2);
    const history: SensorHistory = new Map();
    const o = obs(10, [reading('F1', 'S1', 30, 7), reading('F2', 'S2', 30, 10)]);
    updateHistory(history, o);
    const { trusted, suspect } = checkConsistency(plan, o, ambientEstimate(plan), history);
    expect(suspect).toEqual([{ sensorId: 'F1', reason: 'stale' }]);
    expect(trusted.map((r) => r.sensorId)).toEqual(['F2']);
  });

  it('frozen: a current-looking flat sensor is caught within 8 ticks while neighbors move', () => {
    const plan = line(3);
    const history: SensorHistory = new Map();
    let prev = ambientEstimate(plan);
    let caughtAt: number | null = null;
    // F2 pins at exactly 100.0 with a current t; S1 and S3 climb 6C/tick around it.
    for (let t = 1; t <= 8 && caughtAt === null; t++) {
      const o = obs(t, [
        reading('F1', 'S1', 100 + 6 * t, t),
        reading('F2', 'S2', 100, t),
        reading('F3', 'S3', 90 + 6 * t, t),
      ]);
      updateHistory(history, o);
      const { trusted, suspect } = checkConsistency(plan, o, prev, history);
      if (suspect.some((s) => s.sensorId === 'F2' && s.reason === 'frozen')) caughtAt = t;
      prev = Object.fromEntries(trusted.map((r) => [r.spaceId, r.temp])) as Record<SpaceId, number>;
      prev = { ...ambientEstimate(plan), ...prev };
    }
    expect(caughtAt).not.toBeNull();
    expect(caughtAt!).toBeLessThanOrEqual(8);
  });

  it('impossible-rise: a jump physics cannot produce is dropped', () => {
    const plan = line(2);
    const history: SensorHistory = new Map();
    // Previous belief: everything ambient. F1 suddenly claims 800C. maxRise from 20 is
    // gen 0.25*(900-20) = 220 plus nothing hotter nearby; 780 >> 220 + 6. (Both sensors
    // reported last tick: this is a stationary sensor's jump, not a first observation.)
    updateHistory(history, obs(4, [reading('F1', 'S1', 20, 4), reading('F2', 'S2', 20, 4)]));
    const o = obs(5, [reading('F1', 'S1', 800, 5), reading('F2', 'S2', 21, 5)]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, ambientEstimate(plan), history);
    expect(suspect).toEqual([{ sensorId: 'F1', reason: 'impossible-rise' }]);
  });

  it('impossible-drop: a 450C space "reading ambient" one tick later is dropped', () => {
    const plan = line(2);
    const history: SensorHistory = new Map();
    const prev = { ...ambientEstimate(plan), S1: 450 };
    updateHistory(history, obs(5, [reading('F1', 'S1', 450, 5), reading('F2', 'S2', 25, 5)]));
    const o = obs(6, [reading('F1', 'S1', 21, 6), reading('F2', 'S2', 25, 6)]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, prev, history);
    expect(suspect).toEqual([{ sensorId: 'F1', reason: 'impossible-drop' }]);
  });

  it('cold-in-hot-neighborhood: blinded sensor beside 450C through an open door is dropped', () => {
    const plan = line(3);
    const history: SensorHistory = new Map();
    // S2's estimate is already cold (its sensor has been lying since before the drop
    // rule could catch it), so only the neighborhood contradiction remains.
    const prev = { S1: 450, S2: 22, S3: 450 };
    const o = obs(10, [
      reading('F1', 'S1', 452, 10),
      reading('F2', 'S2', 22, 10), // says ambient while both door-neighbors read 450
      reading('F3', 'S3', 449, 10),
    ]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, prev, history);
    expect(suspect.map((s) => s.reason)).toContain('cold-in-hot-neighborhood');
    expect(suspect.find((s) => s.reason === 'cold-in-hot-neighborhood')!.sensorId).toBe('F2');
  });

  it('no-heat-path: a lone hot reading in an isolated cold neighborhood at t=20 is dropped', () => {
    const plan = line(5);
    const history: SensorHistory = new Map();
    // 220C: hot enough to matter, small enough a rise that only the path rule catches it.
    const moderate = obs(20, [
      reading('F1', 'S1', 21, 20),
      reading('F2', 'S2', 20, 20),
      reading('F3', 'S3', 22, 20),
      reading('F4', 'S4', 20, 20),
      reading('F5', 'S5', 220, 20),
    ]);
    updateHistory(history, moderate);
    const { suspect } = checkConsistency(plan, moderate, ambientEstimate(plan), history);
    expect(suspect).toEqual([{ sensorId: 'F5', reason: 'no-heat-path' }]);
  });

  it('a lone 450C reading from nowhere at t=20 is dropped (rise rule catches it first)', () => {
    const plan = line(5);
    const history: SensorHistory = new Map();
    updateHistory(history, obs(19, [reading('F1', 'S1', 21, 19), reading('F4', 'S4', 20, 19), reading('F5', 'S5', 20, 19)]));
    const o = obs(20, [
      reading('F1', 'S1', 21, 20),
      reading('F4', 'S4', 20, 20),
      reading('F5', 'S5', 450, 20),
    ]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, ambientEstimate(plan), history);
    expect(suspect).toHaveLength(1);
    expect(suspect[0]!.sensorId).toBe('F5');
    expect(['impossible-rise', 'no-heat-path']).toContain(suspect[0]!.reason);
  });

  it('no-heat-path is skipped in the first 3 ticks: the fire has to start somewhere', () => {
    const plan = line(5);
    const history: SensorHistory = new Map();
    const o = obs(1, [reading('F5', 'S5', 450, 1), reading('F1', 'S1', 20, 1)]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, ambientEstimate(plan), history);
    expect(suspect).toEqual([]);
  });

  it('FALSE-POSITIVE GUARD: a clean spreading fire generated by physics itself flags nothing', () => {
    const plan = line(4);
    const history: SensorHistory = new Map();
    let temps: Record<SpaceId, number> = { ...ambientEstimate(plan), S1: 450 };
    let prev = ambientEstimate(plan);
    for (let t = 1; t <= 30; t++) {
      const o = obs(
        t,
        plan.spaces.map((s, i) => reading(`F${i + 1}`, s.id, temps[s.id]!, t)),
      );
      updateHistory(history, o);
      const { trusted, suspect } = checkConsistency(plan, o, prev, history);
      expect(suspect).toEqual([]);
      expect(trusted).toHaveLength(4);
      prev = { ...temps };
      temps = forward(plan, temps, new Set(['S1']));
    }
  });

  describe('moving sensors (drone-borne readings)', () => {
    const drone = (spaceId: string, temp: number, t: number): Reading => ({
      sensorId: 'D1:temp',
      source: 'drone',
      droneId: 'D1',
      spaceId,
      temp,
      t,
    });

    it('a drone reading that jumps from S1 (20 C) to S3 (500 C, matching prevEstimate) is trusted; the same jump on a FIXED sensor id is flagged', () => {
      const plan = line(3);
      // Six ticks parked in S1 at ambient, then a flight into S3 which the brain already
      // believes is at 500 (F3 has been reading it). For the drone that is a move; for a
      // fixed sensor it is a 480 C rise in one tick and physics says no.
      const run = (mk: (spaceId: string, temp: number, t: number) => Reading): ReturnType<typeof checkConsistency> => {
        const history: SensorHistory = new Map();
        const prev = { ...ambientEstimate(plan), S2: 300, S3: 500 };
        let out: ReturnType<typeof checkConsistency> | undefined;
        for (let t = 1; t <= 7; t++) {
          const o = obs(t, [
            mk(t < 7 ? 'S1' : 'S3', t < 7 ? 20 : 500, t),
            reading('F2', 'S2', 300, t),
            reading('F3', 'S3', 500, t),
          ]);
          updateHistory(history, o);
          out = checkConsistency(plan, o, prev, history);
        }
        return out!;
      };
      const d = run(drone);
      expect(d.suspect).toEqual([]);
      expect(d.trusted.map((r) => r.sensorId)).toContain('D1:temp');
      const f = run((spaceId, temp, t) => reading('F1', spaceId, temp, t));
      expect(f.suspect).toEqual([{ sensorId: 'F1', reason: 'impossible-rise' }]);
    });

    it('a drone sitting 8 ticks at one value while the median neighbour moves 100 C is flagged frozen; one that just landed is not', () => {
      const plan = line(3);
      const history: SensorHistory = new Map();
      let prev = ambientEstimate(plan);
      let caughtAt: number | null = null;
      // D1 flies S1 -> S2 at tick 3, then sits in S2 reading exactly 100.0 while S1 and S3 climb.
      for (let t = 1; t <= 11 && caughtAt === null; t++) {
        const o = obs(t, [
          reading('F1', 'S1', 60 + 12 * t, t),
          drone(t < 3 ? 'S1' : 'S2', t < 3 ? 60 + 12 * t : 100, t),
          reading('F3', 'S3', 50 + 12 * t, t),
        ]);
        updateHistory(history, o);
        const { trusted, suspect } = checkConsistency(plan, o, prev, history);
        if (suspect.some((s) => s.sensorId === 'D1:temp' && s.reason === 'frozen')) caughtAt = t;
        else expect(suspect.filter((s) => s.sensorId === 'D1:temp')).toEqual([]);
        prev = { ...ambientEstimate(plan), ...Object.fromEntries(trusted.map((r) => [r.spaceId, r.temp])) };
      }
      // Six flat ticks are needed AFTER the move (ticks 3..8), so nothing before tick 8.
      expect(caughtAt).not.toBeNull();
      expect(caughtAt!).toBeGreaterThanOrEqual(8);
      expect(caughtAt!).toBeLessThanOrEqual(11);
    });

    it('a drone that keeps moving is never frozen even when its reading repeats, and its flight is not counted as its old space moving', () => {
      const plan = line(3);
      const history: SensorHistory = new Map();
      const prev = { ...ambientEstimate(plan), S1: 100, S2: 100, S3: 100 };
      for (let t = 1; t <= 10; t++) {
        // Bounces S1 <-> S2 every tick reading a flat 100 while F3 climbs.
        const o = obs(t, [drone(t % 2 ? 'S1' : 'S2', 100, t), reading('F3', 'S3', 100 + 20 * t, t)]);
        updateHistory(history, o);
        const { suspect } = checkConsistency(plan, o, prev, history);
        expect(suspect.filter((s) => s.reason === 'frozen')).toEqual([]);
      }
    });

    it('stale, cold-in-hot-neighbourhood and no-heat-path apply to drone readings unchanged', () => {
      const plan = line(3);
      // stale
      let history: SensorHistory = new Map();
      let o = obs(10, [drone('S1', 30, 7), reading('F2', 'S2', 30, 10)]);
      updateHistory(history, o);
      expect(checkConsistency(plan, o, ambientEstimate(plan), history).suspect).toEqual([{ sensorId: 'D1:temp', reason: 'stale' }]);
      // cold in a hot neighbourhood: 20 C reading in S2 between two 400 C rooms through open doors
      history = new Map();
      const prev = { ...ambientEstimate(plan), S1: 400, S2: 300, S3: 400 };
      o = obs(10, [reading('F1', 'S1', 400, 10), drone('S2', 20, 10), reading('F3', 'S3', 400, 10)]);
      updateHistory(history, o);
      const cold = checkConsistency(plan, o, prev, history);
      expect(cold.suspect.map((s) => s.reason)).toContain('cold-in-hot-neighborhood');
      expect(cold.suspect.map((s) => s.sensorId)).toEqual(['D1:temp']);
      // no heat path: a drone reporting 300 C in S1 while everything within two edges is cold
      history = new Map();
      const far = line(4);
      o = obs(10, [drone('S1', 300, 10), reading('F2', 'S2', 20, 10), reading('F3', 'S3', 20, 10), reading('F4', 'S4', 20, 10)]);
      updateHistory(history, o);
      const path = checkConsistency(far, o, ambientEstimate(far), history);
      expect(path.suspect).toEqual([{ sensorId: 'D1:temp', reason: 'no-heat-path' }]);
    });

    it('a fixed and a drone reading in the same space both stay trusted when they agree', () => {
      const plan = line(3);
      const history: SensorHistory = new Map();
      const prev = { ...ambientEstimate(plan), S1: 300, S2: 150, S3: 40 };
      const o = obs(10, [reading('F1', 'S1', 301, 10), drone('S1', 299, 10), reading('F2', 'S2', 150, 10), reading('F3', 'S3', 40, 10)]);
      updateHistory(history, o);
      const { trusted, suspect } = checkConsistency(plan, o, prev, history);
      expect(suspect).toEqual([]);
      expect(trusted.filter((r) => r.spaceId === 'S1').map((r) => r.sensorId).sort()).toEqual(['D1:temp', 'F1']);
    });

    it('first observation of a space: a reading from a space nobody observed last tick is not judged against the guessed estimate', () => {
      const plan = line(3);
      // F3 has been the only sensor; S1 is unsensed and the brain guessed it at 60 C. A scout
      // arrives in S1 and reads 500 C: the guess was wrong, the reading is what settles it.
      const history: SensorHistory = new Map();
      const prev = { ...ambientEstimate(plan), S1: 60, S2: 200, S3: 300 };
      for (let t = 5; t <= 8; t++) {
        const o = obs(t, t < 8 ? [reading('F3', 'S3', 300, t), reading('F2', 'S2', 200, t)] : [drone('S1', 500, t), reading('F3', 'S3', 300, t), reading('F2', 'S2', 200, t)]);
        updateHistory(history, o);
        const { suspect } = checkConsistency(plan, o, prev, history);
        expect(suspect).toEqual([]);
      }
      // Whereas a sensor that WAS observed there last tick is held to physics from that estimate.
      const history2: SensorHistory = new Map();
      for (let t = 5; t <= 8; t++) {
        const o = obs(t, [drone('S1', t < 8 ? 60 : 500, t), reading('F3', 'S3', 300, t), reading('F2', 'S2', 200, t)]);
        updateHistory(history2, o);
        const { suspect } = checkConsistency(plan, o, prev, history2);
        if (t === 8) expect(suspect).toEqual([{ sensorId: 'D1:temp', reason: 'impossible-rise' }]);
      }
    });
  });
});
