/**
 * Consistency-rule tests, one hand-built observation sequence per rule, plus the
 * false-positive guard: readings generated by the brain's own physics flag nothing.
 */
import { describe, expect, it } from 'vitest';
import { checkConsistency, updateHistory, type SensorHistory } from './consistency';
import { forward } from './physics';
import type { Observation, Reading, SpaceId, StructurePlan } from '../shared/types';

const line = (n: number, kind: 'door' | 'bulkhead' = 'door'): StructurePlan => ({
  name: `line-${n}`,
  ambient: 20,
  spaces: Array.from({ length: n }, (_, i) => ({ id: `S${i + 1}`, level: 1 })),
  edges: Array.from({ length: n - 1 }, (_, i) => ({ a: `S${i + 1}`, b: `S${i + 2}`, kind, rate: 0.15 })),
  sensors: Array.from({ length: n }, (_, i) => ({ id: `F${i + 1}`, spaceId: `S${i + 1}` })),
  resupply: ['S1'],
  ignition: ['S1'],
});

const reading = (sensorId: string, spaceId: string, temp: number, t: number): Reading => ({
  sensorId,
  source: 'fixed',
  spaceId,
  temp,
  t,
});

const obs = (t: number, readings: Reading[]): Observation => ({ t, readings, drones: [] });

const ambientEstimate = (plan: StructurePlan): Record<SpaceId, number> =>
  Object.fromEntries(plan.spaces.map((s) => [s.id, plan.ambient]));

describe('checkConsistency', () => {
  it('stale: a reading whose t lags obs.t by more than 2 is dropped', () => {
    const plan = line(2);
    const history: SensorHistory = new Map();
    const o = obs(10, [reading('F1', 'S1', 30, 7), reading('F2', 'S2', 30, 10)]);
    updateHistory(history, o);
    const { trusted, suspect } = checkConsistency(plan, o, ambientEstimate(plan), history);
    expect(suspect).toEqual([{ sensorId: 'F1', reason: 'stale' }]);
    expect(trusted.map((r) => r.sensorId)).toEqual(['F2']);
  });

  it('frozen: a current-looking flat sensor is caught within 8 ticks while neighbors move', () => {
    const plan = line(3);
    const history: SensorHistory = new Map();
    let prev = ambientEstimate(plan);
    let caughtAt: number | null = null;
    // F2 pins at exactly 100.0 with a current t; S1 and S3 climb 6C/tick around it.
    for (let t = 1; t <= 8 && caughtAt === null; t++) {
      const o = obs(t, [
        reading('F1', 'S1', 100 + 6 * t, t),
        reading('F2', 'S2', 100, t),
        reading('F3', 'S3', 90 + 6 * t, t),
      ]);
      updateHistory(history, o);
      const { trusted, suspect } = checkConsistency(plan, o, prev, history);
      if (suspect.some((s) => s.sensorId === 'F2' && s.reason === 'frozen')) caughtAt = t;
      prev = Object.fromEntries(trusted.map((r) => [r.spaceId, r.temp])) as Record<SpaceId, number>;
      prev = { ...ambientEstimate(plan), ...prev };
    }
    expect(caughtAt).not.toBeNull();
    expect(caughtAt!).toBeLessThanOrEqual(8);
  });

  it('impossible-rise: a jump physics cannot produce is dropped', () => {
    const plan = line(2);
    const history: SensorHistory = new Map();
    // Previous belief: everything ambient. F1 suddenly claims 800C. maxRise from 20 is
    // gen 0.25*(900-20) = 220 plus nothing hotter nearby; 780 >> 220 + 6.
    const o = obs(5, [reading('F1', 'S1', 800, 5), reading('F2', 'S2', 21, 5)]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, ambientEstimate(plan), history);
    expect(suspect).toEqual([{ sensorId: 'F1', reason: 'impossible-rise' }]);
  });

  it('impossible-drop: a 450C space "reading ambient" one tick later is dropped', () => {
    const plan = line(2);
    const history: SensorHistory = new Map();
    const prev = { ...ambientEstimate(plan), S1: 450 };
    const o = obs(6, [reading('F1', 'S1', 21, 6), reading('F2', 'S2', 25, 6)]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, prev, history);
    expect(suspect).toEqual([{ sensorId: 'F1', reason: 'impossible-drop' }]);
  });

  it('cold-in-hot-neighborhood: blinded sensor beside 450C through an open door is dropped', () => {
    const plan = line(3);
    const history: SensorHistory = new Map();
    // S2's estimate is already cold (its sensor has been lying since before the drop
    // rule could catch it), so only the neighborhood contradiction remains.
    const prev = { S1: 450, S2: 22, S3: 450 };
    const o = obs(10, [
      reading('F1', 'S1', 452, 10),
      reading('F2', 'S2', 22, 10), // says ambient while both door-neighbors read 450
      reading('F3', 'S3', 449, 10),
    ]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, prev, history);
    expect(suspect.map((s) => s.reason)).toContain('cold-in-hot-neighborhood');
    expect(suspect.find((s) => s.reason === 'cold-in-hot-neighborhood')!.sensorId).toBe('F2');
  });

  it('no-heat-path: a lone hot reading in an isolated cold neighborhood at t=20 is dropped', () => {
    const plan = line(5);
    const history: SensorHistory = new Map();
    // 220C: hot enough to matter, small enough a rise that only the path rule catches it.
    const moderate = obs(20, [
      reading('F1', 'S1', 21, 20),
      reading('F2', 'S2', 20, 20),
      reading('F3', 'S3', 22, 20),
      reading('F4', 'S4', 20, 20),
      reading('F5', 'S5', 220, 20),
    ]);
    updateHistory(history, moderate);
    const { suspect } = checkConsistency(plan, moderate, ambientEstimate(plan), history);
    expect(suspect).toEqual([{ sensorId: 'F5', reason: 'no-heat-path' }]);
  });

  it('a lone 450C reading from nowhere at t=20 is dropped (rise rule catches it first)', () => {
    const plan = line(5);
    const history: SensorHistory = new Map();
    const o = obs(20, [
      reading('F1', 'S1', 21, 20),
      reading('F4', 'S4', 20, 20),
      reading('F5', 'S5', 450, 20),
    ]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, ambientEstimate(plan), history);
    expect(suspect).toHaveLength(1);
    expect(suspect[0]!.sensorId).toBe('F5');
    expect(['impossible-rise', 'no-heat-path']).toContain(suspect[0]!.reason);
  });

  it('no-heat-path is skipped in the first 3 ticks: the fire has to start somewhere', () => {
    const plan = line(5);
    const history: SensorHistory = new Map();
    const o = obs(1, [reading('F5', 'S5', 450, 1), reading('F1', 'S1', 20, 1)]);
    updateHistory(history, o);
    const { suspect } = checkConsistency(plan, o, ambientEstimate(plan), history);
    expect(suspect).toEqual([]);
  });

  it('FALSE-POSITIVE GUARD: a clean spreading fire generated by physics itself flags nothing', () => {
    const plan = line(4);
    const history: SensorHistory = new Map();
    let temps: Record<SpaceId, number> = { ...ambientEstimate(plan), S1: 450 };
    let prev = ambientEstimate(plan);
    for (let t = 1; t <= 30; t++) {
      const o = obs(
        t,
        plan.spaces.map((s, i) => reading(`F${i + 1}`, s.id, temps[s.id]!, t)),
      );
      updateHistory(history, o);
      const { trusted, suspect } = checkConsistency(plan, o, prev, history);
      expect(suspect).toEqual([]);
      expect(trusted).toHaveLength(4);
      prev = { ...temps };
      temps = forward(plan, temps, new Set(['S1']));
    }
  });
});
